### ISSUE TITLE
Error in using example

### ISSUE THREAD

**Issue by Rafi993** [iominh/ng-scrollbars#45]
When I did bower install and I installed jquery using bower too . I get the following error 

```

angular.js:13920 TypeError: c.mCustomScrollbar is not a function
    at b (http://localhost:3000/bower_components/ng-scrollbars/dist/scrollbars.min.js:1:288)
    at Object.link (http://localhost:3000/bower_components/ng-scrollbars/dist/scrollbars.min.js:1:912)
    at http://localhost:3000/bower_components/angular/angular.min.js:16:71
    at http://localhost:3000/bower_components/angular/angular.min.js:81:33
    at la (http://localhost:3000/bower_components/angular/angular.min.js:81:90)
    at p (http://localhost:3000/bower_components/angular/angular.min.js:66:341)
    at g (http://localhost:3000/bower_components/angular/angular.min.js:58:481)
    at http://localhost:3000/bower_components/angular/angular.min.js:58:119
    at http://localhost:3000/bower_components/angular/angular.min.js:63:39
    at d (http://localhost:3000/bower_components/angular/angular.min.js:59:474) <tr ng-scrollbars="" ng-scrollbars-config="specsctrl.config" ng-repeat="spec in specsctrl.dat" class="ng-scope ng-isolate-scope" data-ng-animate="1">
```

How to solve this issue thanks in advance

**Comment by while-loop** [comment]
Also getting the same error.

**Comment by alannsiqueira** [comment]
Also getting the same error. [2]

**Comment by katerynajeeva** [comment]
I was getting the same error too, but it dissapeared after I moved 'jquery.js' and 'mCustomScrollbar.js' scripts before 'angular.js'

```
<script src="/js/jquery-2.2.4.min.js"></script>
<script src="/js/jquery.mCustomScrollbar.concat.min.js"></script>
<script src="/js/angular.min.js"></script>
<script src="/js/scrollbars.min.js"></script>
```

**Comment by Rafi993** [comment]
thanks @kate-kholyavkina it worked for me to. I guess it should have been specified in README.md I have given pull request specifying it in README.md so that it would be helpful to others

**Comment by iominh** [comment]
Hey all thanks for the pr, comments, and fix! Currently I'm away but once I get back I'll try to reproduce the issue and do the update

**Comment by flaviorodrigues1977** [comment]
Friends, I followed the tip of our friend Kate-kholyavkina and it worked perfectly!

**Comment by csimpi** [comment]
ahh :( I can't use this plugin with this odd requirement about script files initialize order.

**Comment by Sharique-Hasan** [comment]
How do I use the trick of @kate-kholyavkina with Webpack?
